# Generated by Django 3.2.10 on 2022-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220511_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nom de l icon du site https://fontawesome.com/icons'),
        ),
        migrations.AlterField(
            model_name='service',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='section to show'),
        ),
    ]
