# Generated by Django 3.2.10 on 2022-05-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220511_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='to_home_page',
            field=models.BooleanField(default=False, verbose_name="ajouter a la page d'accueil"),
        ),
    ]
