# Generated by Django 3.2.10 on 2022-05-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_to_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100, verbose_name='site du client')),
                ('image', models.ImageField(upload_to='images/prtfolio ')),
                ('actif', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Formulaire de contact',
                'verbose_name_plural': 'Formulaire de contact',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='function',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
