# Generated by Django 3.2.10 on 2022-05-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_demo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demo',
            options={'ordering': ('id',), 'verbose_name': 'Demo', 'verbose_name_plural': 'Demo'},
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='autor',
            new_name='author',
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Offre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='DAS categorie')),
            ],
            options={
                'verbose_name': 'offre',
                'verbose_name_plural': 'offres',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Fonctionalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Offre')),
                ('prix', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('included', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.offre', verbose_name='DAS categorie')),
            ],
            options={
                'verbose_name': 'fonctionalite',
                'verbose_name_plural': 'fonctionalites',
                'ordering': ('id',),
            },
        ),
    ]
