# Generated by Django 3.2.10 on 2022-05-17 15:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220512_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='texte',
        ),
        migrations.AddField(
            model_name='article',
            name='chapo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='chapô '),
        ),
        migrations.AddField(
            model_name='article',
            name='quote',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='phrase mise en avant '),
        ),
        migrations.AddField(
            model_name='article',
            name='texte_bas',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='texte bas'),
        ),
        migrations.AddField(
            model_name='article',
            name='texte_haut',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='texte haut'),
        ),
        migrations.AddField(
            model_name='fonctionalite',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='article',
            name='aperçu',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='aperçu'),
        ),
    ]
