# Generated by Django 3.2.10 on 2022-05-17 15:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220517_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='texte_haut',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='what we did for ghe client '),
        ),
    ]
