# Generated by Django 3.2.10 on 2022-05-22 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_portfolio_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=False, verbose_name="inclu dans l'offre")),
                ('quantity', models.CharField(max_length=100, verbose_name='quantité')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
                ('fonctionalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fonctionalite', verbose_name='fonctionalite')),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.offre', verbose_name='offre')),
            ],
            options={
                'verbose_name': 'statu',
                'verbose_name_plural': 'status',
                'ordering': ('id',),
            },
        ),
    ]
