# Generated by Django 3.2.10 on 2022-05-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_offre_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='fonctionalite',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.offre'),
        ),
        migrations.AlterField(
            model_name='fonctionalite',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
