# Generated by Django 3.2.10 on 2022-05-23 08:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220523_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonctionalite',
            name='included',
        ),
        migrations.RemoveField(
            model_name='fonctionalite',
            name='number',
        ),
        migrations.RemoveField(
            model_name='fonctionalite',
            name='prix',
        ),
        migrations.AddField(
            model_name='fonctionalite',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
