# Generated by Django 3.2.10 on 2022-05-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220523_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='quantité'),
        ),
    ]
