# Generated by Django 3.2.10 on 2022-05-23 09:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_status_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
