# Generated by Django 3.2.10 on 2022-05-23 09:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_offre_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Déscription du service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pricing',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='offres du service'),
        ),
    ]
