# Generated by Django 3.2.10 on 2022-05-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_status_fonctionalite'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonctionalite',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='ordre / priorité'),
        ),
        migrations.AddField(
            model_name='offre',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='ordre / priorité'),
        ),
    ]
